In [3]:
import numpy as np

## Basics

In [4]:
y = [[1,2,3],[4,5,6],[7,8,9]]
y

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
ny = np.array(y)
ny

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
ny[0][2]

3

In [8]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [9]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [10]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [11]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [12]:

np.logspace(0,5,10)

array([1.00000000e+00, 3.59381366e+00, 1.29154967e+01, 4.64158883e+01,
       1.66810054e+02, 5.99484250e+02, 2.15443469e+03, 7.74263683e+03,
       2.78255940e+04, 1.00000000e+05])

In [14]:
y=np.arange(12)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
y.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
y.reshape(6,-1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

## Create Random Values

In [18]:
np.random.seed(100)

In [19]:
np.random.rand(5)

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [20]:
np.random.rand(5, 3)

array([[0.12156912, 0.67074908, 0.82585276],
       [0.13670659, 0.57509333, 0.89132195],
       [0.20920212, 0.18532822, 0.10837689],
       [0.21969749, 0.97862378, 0.81168315],
       [0.17194101, 0.81622475, 0.27407375]])

In [21]:
a, b = 10, 20
(b-a)*np.random.rand(5)+a

array([14.31704184, 19.4002982 , 18.17649379, 13.3611195 , 11.75410454])

In [22]:
np.random.randint(1,7, size=10)

array([4, 1, 3, 2, 2, 4, 3, 6, 4, 1])

In [23]:
np.random.randint(1, 11, size=(4, 7))

array([[ 2,  1,  8,  7,  3,  1,  9],
       [ 3,  6,  2,  9,  2,  6,  5],
       [ 3,  9,  4,  6,  1, 10,  4],
       [ 7,  4,  5,  8,  7,  4, 10]])

## Create random values in normal distribution

In [24]:
np.random.randn(5)

array([-1.02933685, -0.51099219, -2.36027053,  0.10359513,  1.73881773])

In [25]:
np.random.randn(5, 4)

array([[ 1.24187584,  0.13241276,  0.57779396, -1.57590571],
       [-1.29279424, -0.65991979, -0.87400478, -0.68955061],
       [-0.53547985,  1.52795302,  0.64720579, -0.67733661],
       [-0.2650188 ,  0.74610644, -3.13078483,  0.05962178],
       [-0.87521111,  1.06487833, -0.57315265, -0.80327849]])

### Normal Distribution with $\mu \neq 0$, and $\sigma \neq 1$

In [27]:
m, sigma = 10, 2
m + sigma * np.random.randn(5)

array([12.18594325, 11.30255516, 14.32104958,  8.72173986,  9.33262494])